#!/bin/sh
set -e

cd AndorsTrail

: ${TARGET_OS:=stretch}

ln -s ../travis/support.$TARGET_OS/build.gradle \
	../travis/support/gradle.properties ../travis/support/local.properties .

mkdir -p src/main/assets/translation src/main/java
ln -s ../../AndroidManifest.xml ../../res src/main
ln -s ../../com src/main/java

for po in assets/translation/*.po
do
	msgfmt -o src/main/${po%.po}.mo $po
done

gradle assembleRelease

keytool -genkeypair -v -keystore keystore.p12 -storepass changeit \
	-keypass changeit -storetype pkcs12 -alias self -keyalg RSA \
	-validity 10000 -dname \
	"CN=Unknown, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown"

VERSION=$(grep android:versionCode AndroidManifest.xml | cut -d \" -f 2)
APK=com.gpl.rpg.AndorsTrail_$VERSION.apk

apksigner sign --out $APK -v --ks keystore.p12 --ks-pass pass:changeit \
	build/outputs/apk/AndorsTrail-release-unsigned.apk
apksigner verify $APK
